### ISSUE TITLE
Scitkit-Surgerybk not working after update BK5000

### ISSUE THREAD

**Issue by Nicolaas94** [UCL/scikit-surgerybk#25]
Hi, 

Recently the BK5000 in our hospital has been updated, and now the communication is broken. 
I tried the OpenCV connection from sksurgerybk/interface/bk5000.py. 
Do you have any idea what the problem could be? 
It seems like messages are not correctly coded and decoded from bytes anymore.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 802, in start
  File "<input>", line 682, in get_frame
  File "<input>", line 602, in receive_image
  File "<input>", line 349, in find_first_a_not_preceded_by_b
IndexError: index 0 is out of bounds for axis 0 with size 0

the software version is 5.16.2
distribution build: 6.7.20836.6
HW type: 2304
image update 6.7.20836.6

We would really appreciate your help!

**Comment by thompson318** [comment]
It looks like there might be nothing in the buffer returned from the BK device. The buffer is filled here:
[https://github.com/SciKit-Surgery/scikit-surgerybk/blob/master/sksurgerybk/interface/bk5000.py#L412](https://github.com/SciKit-Surgery/scikit-surgerybk/blob/master/sksurgerybk/interface/bk5000.py#L412)
What happens if you add `print(self.buffer)` at that line?

**Comment by Nicolaas94** [comment]
Thank you very much for helping!

the print command returns:
bytearray(b'')

what could be the cause?

**Comment by thompson318** [comment]
That's an empty bytearray. Looking at lines 408 to 411 that should only happen if the image size is zero. Image size is set by the [parse_win_size_message](https://github.com/SciKit-Surgery/scikit-surgerybk/blob/5b54d743dd0c492f12b6260818380d3ed3ac8912/sksurgerybk/interface/bk5000.py#L192). It looks like there should be a logging message when parse_win_size_message is run, see line [207](https://github.com/SciKit-Surgery/scikit-surgerybk/blob/5b54d743dd0c492f12b6260818380d3ed3ac8912/sksurgerybk/interface/bk5000.py#L207l). Can you check your log file?

**Comment by Nicolaas94** [comment]
Sorry for the late response. The US machine was in use in the clinic. 
I tried with a different US machine, also software version 5.16.2, and I receive image and metadata. 
The problem with the other machine is probably incorrectly installed licences to communicate with the BK5000. 

Once the licensing is done correctly, and communicating is still not possible I will get back to you. 
For now, Thank you very much for your help!
I will close the issue.

**Comment by thompson318** [comment]
Thanks, that sounds plausible.
